[package]
name = "computer-txt"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "computer"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
owo-colors = "4.0.0"

[dev-dependencies]
comrak = "0.27.0"
pretty_assertions = "1.4.0"
